services:
  myhealth:
    image: ghcr.io/asano69/myhealth:latest
    container_name: myhealth
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - myhealth.env
    volumes:
      - ./data:/myhealth/pb_data
        #- /etc/ssl/certs/root_ca.crt:/certs/root_ca.crt:ro # optional
    environment:
      - TZ=Etc/UTC
      #
      - MYHEALTH_SERVER_HOST=0.0.0.0
      - MYHEALTH_SERVER_PORT=3000
      - MYHEALTH_DATA_DIR=pb_data
      #
      #- INITIAL_ADMIN_EMAIL=admin@mail.internal # default
      #- INITIAL_ADMIN_PASSWORD=password # default
volumes:
  data:
